# Generated by Django 5.2 on 2025-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0002_film_rok_alter_film_tytul'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='opis',
            field=models.TextField(default='Opis filmu'),
        ),
    ]
